### ISSUE TITLE
[suggestion] Import by ID

### ISSUE THREAD

**Issue by eleius** [juliusfrost/share-blocked-twitter-accounts#1]
I have a long list of user ids exported using Twitter's blocklist function (it produced a json file which I then converted to a simple list of IDs). I would appreciate it if you could let your app also import user IDs instead of screen names.

Anyway thanks so much for this app, it's super useful since Twitter disabled the import function.

**Comment by juliusfrost** [comment]
Hi, my app actually does this already. If you input a numeric string it interprets it as an ID.

**Comment by eleius** [comment]
That's great! Thanks.
